# -*- coding: utf-8 -*-
"""EDA+feature_eng.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWOYAWahgWaGKO05tiGx3KtoUU5Qrly3
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

df = pd.read_csv("default of credit card clients.csv", header=1)
df.head()

df.rename(columns={'default payment next month': 'default'}, inplace=True)

print(df.columns.tolist())

# Feature grouping
pay_cols = ['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']

bill_cols = [f'BILL_AMT{i}' for i in range(1, 7)]
pay_amt_cols = [f'PAY_AMT{i}' for i in range(1, 7)]

#feature engineering
df['avg_delay'] = df[pay_cols].replace(-2, 0).mean(axis=1)
df['avg_bill'] = df[bill_cols].mean(axis=1)
df['avg_pay'] = df[pay_amt_cols].mean(axis=1)
df['pay_ratio'] = df['avg_pay'] / (df['avg_bill'] + 1)
df['pay_consistency'] = df[pay_amt_cols].std(axis=1)

# Correlation heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(df.corr(numeric_only=True), cmap="coolwarm", linewidths=0.5)
plt.title("Correlation Matrix")
plt.show()

sns.boxplot(x='default', y='avg_delay', data=df)
plt.show()

sns.histplot(df['LIMIT_BAL'], kde=True)
plt.show()

#feature subsets
X_static = df[['LIMIT_BAL', 'AGE', 'avg_delay', 'avg_bill', 'avg_pay', 'pay_ratio', 'pay_consistency']]
X_pca_input = df[pay_cols + bill_cols + pay_amt_cols]
X_seq = df[bill_cols + pay_amt_cols]
y = df['default']

X_train, X_test, y_train, y_test = train_test_split(X_static, y, test_size=0.2, random_state=42)

X_static.to_csv("X_static.csv", index=False)
X_pca_input.to_csv("X_pca_input.csv", index=False)
X_seq.to_csv("X_seq.csv", index=False)
y.to_csv("y.csv", index=False)